services:
  mysql:
    image: mysql:8.4
    container_name: ceara_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ceara_catalog
      MYSQL_USER: ceara_user
      MYSQL_PASSWORD: ceara_pass
      TZ: America/Sao_Paulo
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-proot"]
      interval: 10s
      timeout: 5s
      retries: 10

volumes:
  mysql_data:
